### ISSUE TITLE
Function abandons ACME challenge after 2 sec without reporting an error

### ISSUE THREAD

**Issue by bobmeyers5** [MarcStan/lets-encrypt-azure#10]
After writing the challenge response in the storage account, the function starts calling `POST /acme/chall-v3/111222333/aBcDeF` on the `letsencrypt.org` endpoint. After just 2 seconds and 5 attempts, all of which returned a 200 response code, the function gives up, deletes the response from the storage account, and quietly moves on to process the next certificate in the configuration.

The function should return or log an error indicating why it abandoned the ACME challenge and failed to get the requested certificate.

**Comment by MarcStan** [comment]
Solved with #9
