### ISSUE TITLE
Recommended permissions could (and probably should) be much more limited

### ISSUE THREAD

**Issue by bobmeyers5** [MarcStan/lets-encrypt-azure#11]
The recommended permissions are sufficient for the function to succeed, but they could be much more limited to grant it only the access it actually needs ("least privilege").

I was able to get the function working after granting only the following permissions:

1. Assign function the following **[custom role](https://docs.microsoft.com/en-us/azure/role-based-access-control/tutorial-custom-role-powershell)** on the **resource group** containing the app services:
```
{
    "Name": "App Service SSL Certificate Contributor",
    "IsCustom": true,
    "Description": "Can update App Service certificates and SSL bindings.",
    "Actions": [
        "Microsoft.Web/serverfarms/Write",
        "Microsoft.Web/sites/read",
        "Microsoft.Web/certificates/*",
        "Microsoft.Web/sites/hostnamebindings/*"
    ],
    "NotActions": [],
    "DataActions": [],
    "NotDataActions": [],
    "AssignableScopes": [
      "/subscriptions/<my-subscription-id>"
    ]    
}
```
2. Assign the function the **Key Vault Contributor** role on the **key vault** where the SSL certificates are stored.
3. Assign the function the **Contributor** role on the **storage account** used by the function to store configuration and ACME challenge responses.

You may be able to narrow the permissions even further. My main goal was to avoid assigning the function the **Contributor** role on the entire resource group that contained the app services. That seemed pretty excessive.

**Comment by MarcStan** [comment]
Technically you only needed `Contributor` on the resourcegroup with the app service plan (not the web app). But that only makes sense if the resources are split up.

Instead of `Contributor` the built in roles `Reader` & `Web Plan Contributor` would have also worked.

But I've added your custom rolet to the documentation, thanks!
