### ISSUE TITLE
CdnTargetResoure.IsUsingCertificateAsync throws an unhandled exception without providing useful logging

### ISSUE THREAD

**Issue by godefroi** [MarcStan/lets-encrypt-azure#18]
My automated certificate renewal is failing, and I cannot figure out why. I assume it is a permissions issue, but I don't know which call is failing because the logging is quite minimal. These are the entries I see:

```
[Information]   Working on certificate for: mysite.com;www.mysite.com
[Information]   Certificate mysite-com (from source: mysite-com-keyvault) is still valid until 2/12/2021 9:20:14 PM. Will be renewed in 59 days. Skipping renewal.
[Error]   Certificate renewal failed for: mysite.com;www.mysite.com!
[Information]   Renewing certificates for mysite.com;www.mysite.com took: 00:00:00.6373445
```

Based on these log entries, I believe that the code is failing somewhere in `CdnTargetResoure.IsUsingCertificateAsync`, but without more logging, I cannot tell where. Possibly on line 51 in the call to `_azureCdnClient.GetCustomDomainDetailsAsync`?

The function has the "CDN Profile Reader" and "CDN Endpoint Contributor" on the CDN profile.

**Comment by MarcStan** [comment]
Are you using the latest version of the code? If not you should update:

The Azure CDN endpoints require UTF-8 encoding as of a few weeks ago (before they didn't seem to care). I fixed this in the [latest version (2.0.1)](https://github.com/MarcStan/lets-encrypt-azure/releases/tag/v2.0.1).

As for the logging: Yes in the Azure function logs the output is quite minimal - I tend to rely on app insights as it provides greater detail.

If its not the issue above: Can you see the exceptions in your app insights log?

**Comment by godefroi** [comment]
I forked the code today, so I must have the latest version.

I am not particularly familiar with app insights on Azure, and I'm not good at all at tracking down a coherent log for a single run. I do see a lot of this though:

```
Exception while executing function: renew Failed to process all certificates (Response status code does not indicate success: 403 (Forbidden).) Response status code does not indicate success: 403 (Forbidden). 
```

The failed method is listed as `LetsEncrypt.Logic.Azure.AzureCdnClient+<ListEndpointsAsync>d__2.MoveNext`, which is called int `UpdateAsync`, so probably my original guess at the location was incorrect. It looks like the function is being denied access when listing the endpoints in the CDN profile.

After adding the role "CDN Endpoint Reader", it looks like it succeeds. It would be great if there were a list somewhere of the specific permissions needed; I followed both your blog post and Robert Kroll's, and I missed this one.

**Comment by MarcStan** [comment]
There's documentation for the supported resources and their respective permissions [here](https://github.com/MarcStan/lets-encrypt-azure/blob/master/docs/Supported%20resources.md#azure-cdn-targettypecdn) as well.

I didn't list `CDN Endpoint Reader` because `CDN Endpoint Contributor` should imply reader as well but I'm glad it's working now for you. Perhaps there was some caching issue as well since RBAC changes take up to 10 minutes until they become effective.
