### ISSUE TITLE
Renew certificate if domains changed

### ISSUE THREAD

**Issue by pgampe** [MarcStan/lets-encrypt-azure#19]
Currently the certificates get only renewed when the name changes or the certificate is about to expire.

In addition, it would be nice to also renew a certificate if the list of domains change.

**Comment by MarcStan** [comment]
That's a good idea! It should be easy to auto detect this and force a new certificate issuance.

In the meantime (if need be) you can force override the certificate by passing `newCertificate=true` in the query string when [manually invoking the function](https://github.com/MarcStan/lets-encrypt-azure/blob/master/docs/Setup.md#invoking-the-function-manually).

**Comment by pgampe** [comment]
This works, but it renews all certificates, which results very likely in running into the weekly rate limit for some random certificate covered by this function (if you have many certificates and domains).
So if you find the time, it would also be nice to give the certificate name to be renewed via parameter.

**Comment by MarcStan** [comment]
Done. ;)

And yeah I agree that it's not really practical it was only meant as a workaround (you'd have to manually edit the config as well to only contain the one cert to avoid running into the weekly cert limit of Let's Encrypt).

The implementation wasn't too difficult so I added both features in [2.1.0](https://github.com/MarcStan/lets-encrypt-azure/releases/tag/v2.1.0).
