### ISSUE TITLE
Deployed function project has no job functions

### ISSUE THREAD

**Issue by bobmeyers5** [MarcStan/lets-encrypt-azure#3]
I am trying to deploy this in my Azure environment. I was unable to figure out how to use the `azure-pipelines.yml` file directly, so I manually created build and release pipelines that matched the steps in the YAML file. I omitted the steps related to building and deploying tests.

Everything was going peachy until I deployed the function app. It deployed and loaded successfully, but no job functions were found. Specifically, I see this warning in the trace log during function startup:

_No job functions found. Try making your job classes and methods public. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.)._

This doesn't make sense because I can see the static methods for the "execute" and "renew" functions in the code.

Any ideas what the problem might be?

**Comment by MarcStan** [comment]
Azure DevOps should have YAML pipelines by default now for all new builds. If that's not the case for you then you might you to enable the Multi-stage pipelines preview feature first:

In the top left of Azure DevOps:
![Preview](https://user-images.githubusercontent.com/8313404/69748246-d1e0bd80-113f-11ea-8da5-f4d5a350d9dc.png)

![YAML Pipelines](https://user-images.githubusercontent.com/8313404/69748256-d60cdb00-113f-11ea-8403-cd4244d6d867.png)

Irregardless of that:

The Azure Function runtime requires the build output to be in the correct folder (without nesting). Most likely your build/deployment created an additional folder in the output (usually the project name) and therefore the functions runtime isn't picking up on the endpoints.

You can go to `<your-function>.scm.azurewebsites.net` and browse the files via `Debug console`.

The folder site\wwwroot should look like this:

![3](https://user-images.githubusercontent.com/8313404/69748252-d4dbae00-113f-11ea-84b6-f2f8b1291562.png)

If there is any more nesting try to adjust your deployment to get rid of the folders. Afterwards the Azure function should pick up the endpoints and they should become visible in the portal as well:

![func](https://user-images.githubusercontent.com/8313404/69748491-677c4d00-1140-11ea-8d59-c8a017071abd.png)

**Comment by bobmeyers5** [comment]
Thanks for the detailed response. I checked a bunch of logs and even ran a decompiler on the function .dll to see if the code was actually present, but everything checked out. I eventually just ran the deployment again, and the second time it worked. I have no idea why.
