### ISSUE TITLE
sample.json property "container" should be "containerName"

### ISSUE THREAD

**Issue by bobmeyers5** [MarcStan/lets-encrypt-azure#4]
sample.json contains the following property:
`certificates[0].challengeResponder.properties.container`

However, the corresponding property name in StorageProperties.cs is "ContainerName". This mismatch means the value from the config file is not loaded, resulting in the default value of "$web" instead. I do not have the static website option enabled on my storage account, so this value results in a 403 response and failure to connect to the storage account (RenewalOptionParser.cs, lline 93).

When I changed the config property from "container" to "containerName", the storage connection succeeded.

**Comment by MarcStan** [comment]
Thank you, fixed!
