### ISSUE TITLE
storage path specified in challengeResponder config is not used

### ISSUE THREAD

**Issue by bobmeyers5** [MarcStan/lets-encrypt-azure#5]
sample.json and StorageProperties.cs define a Path property whose default value is `".well-known/acme-challenge/"`. However, this property is never referenced. Instead, the default value is hard-coded in AzureStorageHttpChallengeResponder.cs. So it is not possible to configure the function to use a different storage path.

**Comment by MarcStan** [comment]
Good catch, I just fixed it as well!
