### ISSUE TITLE
execute API does not retry if previous attempt failed to upload to a resource group

### ISSUE THREAD

**Issue by bobmeyers5** [MarcStan/lets-encrypt-azure#6]
I ran the `execute` function, and it succeeded as far as getting a valid certificate issued. When it tried to upload to the target resource group, however, an authorization error occurred. Subsequent attempts to run the `execute` function returned successfully without retrying this operation, because a valid certificate was already present in the KeyVault.

I assume the `newCertificate` query parameter could be used to force a fully retry, but it might be better for the function not to assume the previous attempt completed successfully if the certificate was not successfully uploaded to the resource group and the binding configured in the app service.

**Comment by MarcStan** [comment]
Actually you can use `updateResource` query parameter to just force updating the resource with the existing certificate.

I agree however that the function could query the resource to check if the latest certificate is in use instead of silently skipping it.

**Comment by MarcStan** [comment]
I've made the app service certificate process idempotent (if it fails at any point it will retry on next run).

I also remember now why I didn't do this from the begining: There are some issues with the CDN endpoint that I still have to work around (the 6h update time window in which all API calls return BadRequest for starters..).

But this issue should be fixed.
