### ISSUE TITLE
New certificate order fails with 429, but function quietly continues

### ISSUE THREAD

**Issue by bobmeyers5** [MarcStan/lets-encrypt-azure#9]
When attempting to issue a new certificate, `https://acme-v02.api.letsencrypt.org/acme/new-order` is returning a 429 status code. This is likely due to one of the [rate-limiting rules](https://letsencrypt.org/docs/rate-limits/) enforced by the service, but the function does not log or return an error when this occurs. Instead, it quietly skips that certificate and proceeds to the next one in the config file. The only hint at why the certificate was being skipped was the dependency telemetry that indicated the external HTTP call and the 429 response.

The function should log an error in this case, along with the reason for the 429 response (it looks like Certes tries to return quite a bit of [error detail](https://github.com/fszlin/certes/blob/master/src/Certes/Acme/AcmeError.cs) in `AcmeHttpResponse.Error`).

**Comment by MarcStan** [comment]
Hm, this must have happend recently as errors (also those mentioned in #10) used to be logged (both in the function logs and app insights).

I applied the fix/workaround mentioned [here](https://github.com/Azure/Azure-Functions/issues/1256#issuecomment-505478565) to the function [host json](https://github.com/MarcStan/lets-encrypt-azure/blob/master/LetsEncrypt.Func/host.json).

Logging seems to work again both locally and in Azure with that fix. Can you confirm?
___
FYI: I switched over the function to .Net Core 3 and functions v3 runtime.

The relevant changes are in these commits [ace12dac73d850a084304300222a462bf7efc182](https://github.com/MarcStan/lets-encrypt-azure/commit/ace12dac73d850a084304300222a462bf7efc182) & [377a3ff6a691dc6530ecc60ab9ac61f967cdb725](https://github.com/MarcStan/lets-encrypt-azure/commit/377a3ff6a691dc6530ecc60ab9ac61f967cdb725). At the very least you must set version "~3" on your function app as well).

**Comment by bobmeyers5** [comment]
I deployed your latest, and I'm seeing traces in Application Insights now, which I believe were missing before. However, neither the 429 response nor the "abandon ACME challenge" behavior are happening anymore (probably due to other factors), so I can't verify whether those particular code paths generate helpful logs now.

**Comment by MarcStan** [comment]
You probably hit the lowest [rate limit](https://letsencrypt.org/docs/rate-limits/):

> There is a Failed Validation limit of 5 failures per account, per hostname, per hour.

To verify exceptions are logged correctly I disabled `Blob Storage Contributor` and forced a renew, causing this exception to show up in app insights:

> Expected all challenges to be in status Valid, but 1 where not: Invalid response from http://letsencrypt-inttest.marcstan.net/.well-known/acme-challenge/\<id>: "\<!DOCTYPE html>\<html>\<head>\<title>WebContentNotFound\</title>\</head>\<body>\<h1>The requested content does not exist.\</h1>\<p>\<ul>" 

___
For testing/setting up a domain I recommend you use `"staging": true` in the config. This will not issue real certs but has higher [rate limits](https://letsencrypt.org/docs/staging-environment/).

Otherwise you might block yourself from generating new certificates for a certain domain for a week!
